### ISSUE TITLE
How about icons on windows toolbar

### ISSUE THREAD

**Issue by abnerlee** [icons8/windows-10-icons#1]
How about traffic light icons on windows 10 toolbar ? It will be helpful if someone add them to the icon set.

![snip20150807_1](https://cloud.githubusercontent.com/assets/1621242/9130509/0f284896-3d16-11e5-9d1c-79e19db6ca70.png)

**Comment by visualpharm** [comment]
That's interesting. Don't you use the standard controls?

**Comment by abnerlee** [comment]
Just some thoughts. I may want to pop up some HTML dialogs from my web page/app. So unified icon set is prefered.
